#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import sys
import os
import time
import subprocess
import json
import psutil

ResultJsonPath = "runner.json"
StdinPath = "stdin.txt"
StdoutPath = "stdout.txt"
StderrPath = "stderr.txt"
RunAs = "runner" # set to None if use root or not on linux

def clearFiles():
	if os.path.isfile(ResultJsonPath):
		os.unlink(ResultJsonPath)
	if os.path.isfile(StdoutPath):
		os.unlink(StdoutPath)
	if os.path.isfile(StderrPath):
		os.unlink(StderrPath)

def writeResult(obj):
	with open(ResultJsonPath, "wb") as result:
		jsonBytes = json.dumps(obj).encode("utf-8")
		result.write(jsonBytes)
		result.write(b"\n")

def nowInMillisecond():
	return int(time.time() * 1000)

def killRecursive(psutilProc):
	"""kill process and it's childs"""
	try:
		for childProc in psutilProc.children(recursive=True):
			try:
				childProc.kill()
			except psutil.NoSuchProcess:
				pass
		psutilProc.kill()
	except psutil.NoSuchProcess:
		pass

def killUser(username):
	"""kill processes under specific user"""
	if username is None or username == "root":
		return
	# stop first, then kill, it's very effective for fork bomb with nproc limit
	killSet = set()
	killSetSize = None
	while (killSetSize is None) or (killSetSize < len(killSet)):
		killSetSize = len(killSet)
		for proc in psutil.process_iter():
			try:
				if proc.username() == username:
					proc.suspend()
					killSet.add(proc.pid)
					# print("stopped %s"%proc.pid)
			except psutil.NoSuchProcess:
				pass
	killCount = None
	while (killCount is None) or (killCount > 0):
		killCount = 0
		for proc in psutil.process_iter():
			try:
				if proc.username() == username:
					proc.kill()
					killCount += 1
					# print("killed %s"%proc.pid)
			except psutil.NoSuchProcess:
				pass

def getUsedMemoryInBytes(psutilProc):
	"""get maximum used memory in bytes from process and it's childs, return RSS not VMS"""
	try:
		rss = psutilProc.memory_info().rss
		for childProc in psutilProc.children(recursive=True):
			try:
				rss = max(rss, childProc.memory_info().rss)
			except psutil.NoSuchProcess:
				pass
		return rss
	except psutil.NoSuchProcess:
		return 0

def getUserTimeInMilliseconds(psutilProc):
	"""get maximum user time in milliseconds from process and it's childs"""
	try:
		userTime = psutilProc.cpu_times().user
		for childProc in psutilProc.children(recursive=True):
			try:
				userTime = max(userTime, childProc.cpu_times().user)
			except psutil.NoSuchProcess:
				pass
		return int(userTime * 1000)
	except psutil.NoSuchProcess:
		return 0

def run(userLimitMs, totalLimitMs, cmdline):
	userTime = 0
	totalTime = 0
	peakMemory = 0 # RSS, not VMS
	exitCode = None
	isTimeout = False
	error = ""
	cmdOption = [ "su", RunAs, "-c", cmdline ] if RunAs else cmdline
	shellOption = False if RunAs else cmdline
	if not os.path.isfile(StdinPath):
		open(StdinPath, "wb").close()
	with open(StdinPath, "rb") as stdin, open(StdoutPath, "wb") as stdout, open(StderrPath, "wb") as stderr:
		startTime = nowInMillisecond()
		proc = subprocess.Popen(
			cmdOption,
			shell=shellOption,
			stdin=stdin,
			stdout=stdout,
			stderr=stderr)
		try:
			psutilProc = psutil.Process(proc.pid)
		except psutil.NoSuchProcess:
			pass
		while True:
			exitCode = proc.poll()
			if exitCode is not None:
				break
			if psutilProc is None:
				error = "process exist but get it's information failed"
				break
			peakMemory = max(peakMemory, getUsedMemoryInBytes(psutilProc))
			userTime = max(userTime, getUserTimeInMilliseconds(psutilProc))
			if userTime > userLimitMs:
				isTimeout = True
				error = "killed by timeout(user)"
				killRecursive(psutilProc)
				break
			if nowInMillisecond() - startTime > totalLimitMs:
				isTimeout = True
				error = "killed by timeout(total)"
				killRecursive(psutilProc)
				break
			time.sleep(0.001)
		exitCode = proc.poll()
		totalTime = nowInMillisecond() - startTime
	if exitCode is None:
		exitCode = -1 # kill signal sent but still exist
	killUser(RunAs) # cleanup
	if exitCode != 0 and not error:
		with open(StderrPath, "rb") as stderr:
			errorBytes = stderr.read()
			try:
				error = errorBytes.decode("utf-8")
			except UnicodeDecodeError:
				pass
	writeResult({
		"Command": cmdline,
		"UserTime": userTime,
		"TotalTime": totalTime,
		"PeakMemory": peakMemory, # maybe 0 if process exited so quick
		"ExitCode": exitCode,
		"IsTimeout": isTimeout,
		"Error": error
	})

def main():
	"""
		Input:
			First Line: user_time_limit_in_milliseconds [total_time_limit_in_milliseconds]
			Second Line: command_line
			stdin.txt (optional)
		Output:
			stdout.txt
			stderr.txt
			runner.json
	"""
	limitTimeMs = 0
	cmdline = ""
	try:
		clearFiles()
		limitMs = input().split()
		cmdline = input()
		userLimitMs = int(limitMs[0])
		totalLimitMs = int(limitMs[1]) if (len(limitMs) > 1) else (userLimitMs * 2)
		run(userLimitMs, totalLimitMs, cmdline)
	except Exception as e:
		writeResult({
			"Command": cmdline,
			"UserTime": 0,
			"TotalTime": 0,
			"PeakMemory": 0,
			"ExitCode": -1,
			"IsTimeout": False,
			"Error": repr(e)
		})

if __name__ == "__main__":
	main()
